import 'common.dart';

const exampleProfilePicture = 'https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D';

List<Playdate> examplePlaydates = const [
  Playdate(
    location: 'Pinnacles National Park',
    title: 'Hiking Adventure',
    author: 'Kevin T',
    description: 'Join us for a breathtaking hike through the Pinnacles National Park.',
    imageUrl: 'https://images.unsplash.com/photo-1651425268754-aa426f533e28',
    imageAltText: 'Image of rock formations along a scenic hike at Pinnacles National Park.',
    tags: {'Hiking', 'Outdoor', 'Adventure', 'National Park', 'Scenic Views', 'Fitness', 'Nature', 'Explore'},
    price: PlaydatePrice.FREE,
    duration: '4h',
  ),
  Playdate(
    location: 'Local Park',
    title: 'Picnic in the Park',
    author: 'Nicole S',
    description: 'Enjoy a relaxing picnic with great food and company.',
    imageUrl: 'https://images.unsplash.com/photo-1593034509785-5b17ba49f683?q=80&w=2574&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'Image of a lot of different pastries on a picnic blanket in a park.',
    tags: {'Picnic', 'Relax', 'Food', 'Friends', 'Outdoor', 'Family', 'Chill', 'Park'},
    price: PlaydatePrice.FREE,
    duration: '2h',
  ),
  Playdate(
    location: 'Stanford Dining Hall',
    title: 'Culinary Experience at Stanford',
    author: 'ChefAmanda',
    imageUrl: 'https://images.unsplash.com/photo-1691189292321-239dac61cf81?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'Image of Arillaga Family Dining Commons',
    description: 'Explore the diverse flavors offered by the renowned chefs at Stanford\'s Dining Hall.',
    tags: {'Food', 'Dining', 'Culinary', 'University', 'Experience', 'Gourmet', 'Campus Life', 'Taste'},
    price: PlaydatePrice.$$,
    duration: '1h 30m',
  ),
  Playdate(
    location: 'City Sports Center',
    title: 'Community Swim Meet',
    author: 'CoachBob',
    description: 'Dive into fun at our annual community swim meet. All ages welcome!',
    imageUrl: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'A swimmer doing freestyle in a pool.',
    tags: {'Swimming', 'Fitness', 'Community', 'Sports', 'Water', 'Fun', 'Health'},
    price: PlaydatePrice.$,
    duration: '3h',
  ),
  Playdate(
    location: 'Downtown Art Gallery',
    title: 'Modern Art Exhibition',
    author: 'ArtEnthusiast',
    description: 'Experience the avant-garde in our exhibit featuring local modern artists.',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1682088715035-11e11e28f50f?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'A man looking at different paintings in an art gallery.',
    tags: {'Art', 'Exhibition', 'Culture', 'Gallery', 'Modern', 'Creative', 'Local Artists', 'Inspiration'},
    price: PlaydatePrice.$,
    duration: '2h',
  ),
  Playdate(
    location: 'Mountain Trail',
    title: 'Sunrise Yoga Session',
    author: 'YogaMaster',
    description: 'Start your day with tranquility and a stunning mountain sunrise during our yoga session.',
    imageUrl: 'https://images.unsplash.com/photo-1447452001602-7090c7ab2db3?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'A woman doing a yoga pose on a mountain.',
    tags: {'Yoga', 'Wellness', 'Sunrise', 'Mountain', 'Peace', 'Meditation', 'Exercise', 'Nature'},
    price: PlaydatePrice.$,
    duration: '1h',
  ),
  Playdate(
    location: 'Beachside Boulevard',
    title: 'Salty Sprint 5K Run',
    author: 'RunClubLeader',
    description: 'Join our beachside 5K and run with the ocean breeze at your back.',
    imageUrl: 'https://images.unsplash.com/photo-1596460658047-1826d5921c56?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'A group of runners running beside palm trees on a beach.',
    tags: {'Running', '5K', 'Beach', 'Race', 'Fitness', 'Outdoor', 'Community Event', 'Athletic'},
    price: PlaydatePrice.FREE,
    duration: '1h',
  ),
  Playdate(
    location: 'Local Library',
    title: 'Mystery Book Club',
    author: 'LiterateLinda',
    description: 'Discuss the latest mystery novels with fellow enthusiasts at our monthly book club.',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1681681082145-8e0765ddc770?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'Two women reading together at a library',
    tags: {'Reading', 'Book Club', 'Mystery', 'Discussion', 'Community', 'Library', 'Learning', 'Novels'},
    price: PlaydatePrice.FREE,
    duration: '2h',
  ),
  Playdate(
    location: 'Riverside Park',
    title: 'Outdoor Concert Series',
    author: 'MusicMan',
    description: 'Enjoy live music in the park every weekend. Bring a blanket and unwind under the sky.',
    imageUrl: 'https://images.unsplash.com/photo-1472653816316-3ad6f10a6592?q=80&w=2669&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'People sitting at an outdoor music event on picnic blankets',
    tags: {'Music', 'Concert', 'Live', 'Outdoor', 'Park', 'Entertainment', 'Nightlife', 'Relax'},
    price: PlaydatePrice.$,
    duration: '4h',
  ),
  Playdate(
    location: 'TechSpace Makerspace',
    title: 'Robotics Workshop for Beginners',
    author: 'TechGuru',
    description: 'Dive into the world of robotics with our hands-on workshop designed for beginners.',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1682124389443-faa964f770c9?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'A picture of a robot being observed and operated by a group of people.',
    tags: {'Robotics', 'Workshop', 'Tech', 'Makerspace', 'DIY', 'Education', 'Innovation', 'Learning'},
    price: PlaydatePrice.$$,
    duration: '3h',
  ), Playdate(
    location: 'Gourmet Sky Dining',
    title: 'Dining in the Skies',
    author: 'LuxEventPlanner',
    description: 'Enjoy a gourmet dinner served in a private capsule on the iconic city skyline Ferris wheel.',
    imageUrl: 'https://images.unsplash.com/photo-1566571875437-23fa2e2ba76d?q=80&w=2696&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'A woman enjoying a meal with a gorgeous city view.',
    tags: {'Luxury', 'Fine Dining', 'Skyline', 'Romantic', 'Exclusive', 'Gourmet', 'Views', 'Young Adults'},
    price: PlaydatePrice.$$$,
    duration: '2h',
  ),
  Playdate(
    location: 'Elite Yacht Club',
    title: 'Sunset Sailing Experience',
    author: 'CaptainLuxury',
    description: 'Embark on a luxurious sailing journey with stunning sunsets and gourmet refreshments on board.',
    imageUrl: 'https://images.unsplash.com/photo-1605281317010-fe5ffe798166?q=80&w=2644&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'A large yacht in the water.',
    tags: {'Yacht', 'Sailing', 'Luxury', 'Sunset', 'Exclusive', 'Sea', 'Young Adults', 'Adventure'},
    price: PlaydatePrice.$$$,
    duration: '4h',
  ),
  Playdate(
    location: 'Mountaintop Resort',
    title: 'VIP Heliskiing Adventure',
    author: 'ExtremeExcursions',
    description: 'Experience the rush of heliskiing on untouched powder with our exclusive mountain resort package.',
    imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    imageAltText: 'A picture of a resort tucked in between different mountains.',
    tags: {'Heliskiing', 'Snow', 'Luxury', 'Adventure', 'Exclusive', 'Mountains', 'Ski', 'Young Adults'},
    price: PlaydatePrice.$$$,
    duration: 'Full Day',
  )
];
